#ifndef MENU_VENTAS_H_
#define MENU_VENTAS_H_

typedef enum VENTAS_ERRORS {ERR_VENTAS_OK, ERR_INVALID_VENTAS} VENTAS_ERRORS;
typedef enum VENTAS_OP {
    VENTAS_END,
    VENTAS_LISTAR,
    VENTAS_BUSCAR_TITULO,
    VENTAS_BUSCAR_AUTOR_NOMBRE,
    VENTAS_BUSCAR_AUTOR_APELLIDO,
    VENTAS_BUSCAR_ISBN,
} VENTAS_OP;
void ventasMenu();
VENTAS_ERRORS validVentasOption(enum VENTAS_OP option);

#endif // MENU_VENTAS_H_
